Feature/search
slothdeboss/EnEfTe pull request #9
Opened 2023-10-29 18:44 UTC by slothdeboss

2023-10-29 20:48 UTC, bohdanzdaniekin requested changes

2023-10-29 20:48 UTC, bohdanzdaniekin commented on app/src/main/java/com/slothdeboss/enefte/ui/screens/discover/DiscoverScreen.kt
> +                        rows = GridCells.Fixed(count = 2),
@slothdeboss Probably, it would be more readable if we extract it into function or introduce some constants

2023-10-29 20:48 UTC, bohdanzdaniekin commented on app/src/main/java/com/slothdeboss/enefte/ui/components/util/ComponentSize.kt
> +@Stable
@slothdeboss are you sure?
https://developer.android.com/jetpack/compose/performance/stability#types
if I understood the article correctly,
we can have only one of the following cases
```kotlin
@Immutable
data class ComponentSize(
    val width: Dp,
    val height: Dp
)
```
Or
```
@Stable
class ComponentSize(
    width: Dp,
    height: Dp
) {
    var width by mutableStateOf(width)
        private set

    var height by mutableStateOf(height)
        private set

    fun setWidth(width: Dp) {
        this.width = width
    }

    fun setHeight(height: Dp) {
        this.height = height
    }
}
```

2023-10-29 20:48 UTC, bohdanzdaniekin commented on app/src/main/java/com/slothdeboss/enefte/ui/components/util/ComponentSize.kt
> +data class ComponentSize(
@slothdeboss also seems like we can use the already existing `DpSize `class instead

2023-11-03 19:41 UTC, igel911 approved these changes

2023-11-07 19:22 UTC, merged